# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir c:/users/emily/documents/document/2015-2016/ece532/project/hex/ip_repo/edit_HEX_v1_0.cache/wt [current_project]
set_property parent.project_path c:/users/emily/documents/document/2015-2016/ece532/project/hex/ip_repo/edit_HEX_v1_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/Emily/Documents/Document/2015-2016/ECE532/Project/HEX/ip_repo/HEX_1.0 [current_project]
read_verilog -library xil_defaultlib {
  c:/users/emily/documents/document/2015-2016/ece532/project/hex/ip_repo/hex_1.0/hdl/HEX_v1_0.v
  c:/users/emily/documents/document/2015-2016/ece532/project/hex/ip_repo/hex_1.0/hdl/HEX_v1_0_HEX_AXI.v
  C:/Users/Emily/Documents/Document/2015-2016/ECE532/Project/HEX/ip_repo/HEX_1.0/hdl/sevensegdecoder.v
  C:/Users/Emily/Documents/Document/2015-2016/ECE532/Project/HEX/ip_repo/HEX_1.0/hdl/decoder3_8.v
  C:/Users/Emily/Documents/Document/2015-2016/ECE532/Project/HEX/ip_repo/HEX_1.0/hdl/counter3bit.v
  C:/Users/Emily/Documents/Document/2015-2016/ECE532/Project/HEX/ip_repo/HEX_1.0/hdl/segClkDevider.v
  C:/Users/Emily/Documents/Document/2015-2016/ECE532/Project/HEX/ip_repo/HEX_1.0/hdl/mux4_4bus.v
  C:/Users/Emily/Documents/Document/2015-2016/ECE532/Project/HEX/ip_repo/HEX_1.0/hdl/DigitToSeg.v
}
synth_design -top HEX_v1_0 -part xc7a100tcsg324-1
write_checkpoint -noxdef HEX_v1_0.dcp
catch { report_utilization -file HEX_v1_0_utilization_synth.rpt -pb HEX_v1_0_utilization_synth.pb }
