# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    set ::env(RT_TMP) "./.Xil/Vivado-7012-Emily-PC/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a100tcsg324-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      c:/users/emily/documents/document/2015-2016/ece532/project/hex/ip_repo/hex_1.0/hdl/HEX_v1_0.v
      c:/users/emily/documents/document/2015-2016/ece532/project/hex/ip_repo/hex_1.0/hdl/HEX_v1_0_HEX_AXI.v
      C:/Users/Emily/Documents/Document/2015-2016/ECE532/Project/HEX/ip_repo/HEX_1.0/hdl/sevensegdecoder.v
      C:/Users/Emily/Documents/Document/2015-2016/ECE532/Project/HEX/ip_repo/HEX_1.0/hdl/decoder3_8.v
      C:/Users/Emily/Documents/Document/2015-2016/ECE532/Project/HEX/ip_repo/HEX_1.0/hdl/counter3bit.v
      C:/Users/Emily/Documents/Document/2015-2016/ECE532/Project/HEX/ip_repo/HEX_1.0/hdl/segClkDevider.v
      C:/Users/Emily/Documents/Document/2015-2016/ECE532/Project/HEX/ip_repo/HEX_1.0/hdl/mux4_4bus.v
      C:/Users/Emily/Documents/Document/2015-2016/ECE532/Project/HEX/ip_repo/HEX_1.0/hdl/DigitToSeg.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top HEX_v1_0
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
    rt::set_parameter webTalkPath {c:/users/emily/documents/document/2015-2016/ece532/project/hex/ip_repo/edit_HEX_v1_0.cache/wt}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-7012-Emily-PC/"
    if {$rt::useElabCache == false} {
      rt::run_synthesis -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
    }


    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
